# Generated by Django 2.2 on 2020-12-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0002_flowers_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowers',
            name='image',
            field=models.ImageField(upload_to='home/alex/code/roma/roma/flowers/static/image'),
        ),
    ]
